# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci_sum():
    n1 = 1
    n2 = 2
    n3 = 0
    sum = n2
    print("{}, {}".format(n1,n2), end=", ")
    while n1 + n2 < 4000000:
        n3 = n1 + n2
        n1 = n2
        n2 = n3
        print("{}".format(n3), end=", ")
        if (n3 % 2 == 0):
            sum += n3
    return sum

print("\nsum: " + str(fibonacci_sum()))